### ISSUE TITLE
Error during "go mod vendor" to build in an offline environment

### ISSUE THREAD

**Issue by darix** [smallstep/cli#377] opened 2020-10-22 21:00 UTC
### Subject of the issue

While trying to prepare a vendor tarball for building 0.15.3

```
go: finding module for package google.golang.org/grpc/naming
github.com/smallstep/cli/command/certificate imports
	github.com/smallstep/certinfo imports
	github.com/google/certificate-transparency-go imports
	go.etcd.io/etcd imports
	github.com/coreos/etcd/etcdmain imports
	github.com/coreos/etcd/proxy/grpcproxy imports
	google.golang.org/grpc/naming: module google.golang.org/grpc@latest found (v1.33.1), but does not contain package google.golang.org/grpc/naming
```

### Your environment
* OS - openSUSE Tumbleweed
* Version - go 1.14.0

### Steps to reproduce

```
tar xf cli-0.15.3.tar.gz
cd cli*/
go mod vendor
```

### Expected behaviour

```go mod vendor``` succeeds

### Actual behaviour

Errors out

**Comment by maraino** [comment] 2020-10-22 22:05
I've seen the same when doing `go mod tidy`. It looks like we need to upgrade some dependency to solve this.

**Comment by maraino** [comment] 2020-10-25 18:39
Probably related to https://github.com/etcd-io/etcd/issues/12124

**Comment by maraino** [comment] 2020-12-01 02:30
@darix We're going to merge a temporary workaround to fix the dependency issue caused by etcd. Once that's merged, it should be possible to run `go mod vendor`.

This fix should be removed once the issue mentioned above gets fixed.

**Closed** 2020-12-01 02:34 UTC
Labels: bug
