### ISSUE TITLE
SAN option ignored when creating a ca certificate

### ISSUE THREAD

**Issue by rauljmz** [smallstep/cli#91] opened 2019-03-04 21:06 UTC
### Subject of the issue
When trying to create certificate, the san option seems to get ignored

### Your environment
* OS - Docker step-cli image
* Version - 0.8.6

### Steps to reproduce
Having a ca available and configured, from the cli do:
```
step ca certificate --san foo --san bar foobar foobar.crt foobar.key
step certificate inspect foobar.crt
```

### Expected behaviour
The `X509v3 Subject Alternative Name:` should list 
```
DNS:foo
DNS:bar
```

### Actual behaviour
The `X509v3 Subject Alternative Name:` lists
```
DNS:foobar
```

**Comment by maraino** [comment] 2019-03-04 21:28
Hi @rauljmz I think the problem is that your step-ca (certificates) is not up-to-date, it's probably using a version that didn't support multiple SANs.

**Comment by rauljmz** [comment] 2019-03-04 21:31
Great thanks @maraino. I was using your official docker image smallstep/step-ca:latest pulled this morning. Should I make my own image instead?

**Comment by maraino** [comment] 2019-03-04 21:32
I'll reopen the issue, just in case we haven't pushed a new version.

**Comment by maraino** [comment] 2019-03-04 22:13
@rauljmz: the problem is that we haven't updated the `:latest` tag, the version you are using is one of the first public versions.

Right now you can change the tag to use the tag `:0.8.5`, but that won't be enough, that image does not contain the ca configuration, certificates, and keys. You can create them with `step ca init` and add it to your custom image. 

I'm closing this ticket and we'll open a new ticket to update the `:latest` tag and add documentation for how to run your docker image.

**Closed by maraino** 2019-03-04 22:13 UTC
