### ISSUE TITLE
[Bug]: Rekeying a JWK provisioner fails

### ISSUE THREAD

**Issue by tashian** [smallstep/cli#1199] opened 2024-06-13 15:08 UTC
### Steps to Reproduce

```
step ca init
step-ca
```

Then, in another terminal:

```
step ca provisioner update [jwk provisioner name] --create
```

### Your Environment

* OS - darwin
* `step` CLI Version -0.26.0

### Expected Behavior

It should have rekeyed the provisioner and asked me for a new password.

### Actual Behavior

CLI output:

```
✔ CA Configuration: /Users/carl/.step/authorities/test/config/ca.json

Please enter a password to encrypt the provisioner private key? [leave empty and we'll generate one]:
error updating provisioner: error updating provisioner 'carl@smallstep' in authority cache: provisioner carl@smallstep:8MsJE2JtORIf-pQJnW9TWp1mrMqXPH3wg_oGo_gqSks not found
```

step-ca output:

```
WARN[0144]                                               duration="17.334µs" duration-ns=17334 fields.time="2024-06-12T14:46:47-07:00" method=GET name=ca path=/admin/admins protocol=HTTP/2.0 referer= remote-address="::1" request-id=32bf204e-7c25-4a24-ab97-2e99656c31a3 size=19 status=404 user-agent="Smallstep CLI/0.26.0 (darwin/arm64)" user-id=
```

### Additional Context

This is without remote provisioner management enabled.

@dopey took a look at this one, confirmed it, and found the source of the error.

### Contributing

Vote on this issue by adding a 👍 reaction.
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by hslatman** [comment] 2024-06-19 11:15
This seems to be a duplicate of #1059

**Closed** 2024-06-24 20:44 UTC
Labels: bug, needs triage

**Comment by tashian** [comment] 2024-06-24 20:46
I resurfaced #1059 on the triage board. It was already in To Do.
