### ISSUE TITLE
TestParseKey fails error 'alg 'EdDSA' is not compatible with the given key' not expected

### ISSUE THREAD

**Issue by eclipseo** [smallstep/cli#217] opened 2020-02-11 02:49 UTC
### Your environment
* OS - Fedora Rawhide
* Version - Go 1.14 beta1, jose 2.4.1

### Subject of the issue

```
github.com/smallstep/cli/jose
--- FAIL: TestParseKey (0.69s)
    parse_test.go:92: error 'alg 'EdDSA' is not compatible with the given key' not expected
    parse_test.go:102: type 'ed25519.PrivateKey' expected and found 'ed25519.PrivateKey'
    parse_test.go:92: error 'alg 'EdDSA' is not compatible with the given key' not expected
    parse_test.go:100: type 'ed25519.PublicKey' expected and found 'ed25519.PublicKey'
    parse_test.go:92: error 'alg 'EdDSA' is not compatible with the given key' not expected
    parse_test.go:102: type 'ed25519.PrivateKey' expected and found 'ed25519.PrivateKey'
    parse_test.go:90: error 'error generating JWK thumbprint: square/go-jose: unknown key type 'ed25519.PrivateKey'' not expected
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x555c266271d8]
```

**Comment by maraino** [comment] 2020-02-11 03:36
@eclipseo It's weird, I've tested and I'm not able to reproduce it on:
* macOS with Go `1.13.6` and `1.14rc1`, and both go-jose `2.4.0` and `2.4.1`
* ubuntu with Go `1.13.7` and go-jose `2.4.0`

**Comment by sourishkrout** [comment] 2020-06-03 17:21
Closing since we failed to repro. Feel free to re-open with instructions how to repro @eclipseo.

**Closed by sourishkrout** 2020-06-03 17:21 UTC
